export const Books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    cover: "https://img.freepik.com/free-vector/bike-guy-wattpad-book-cover_23-2149452163.jpg",
    description: "A novel set in the Roaring Twenties that explores themes of decadence, idealism, resistance to change, social upheaval, and excess.",
    rating: 4.2,
    feature: true,
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    cover: "https://img.freepik.com/free-vector/vintage-book-cover-design_23-2149492190.jpg",
    description: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
    rating: 4.7,
    feature: false,
  },
  {
    id: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    cover: "https://img.freepik.com/free-vector/flat-design-literature-book-cover-template_23-2149445496.jpg",
    description: "A novel about the serious issues of rape and racial inequality, told through the eyes of a child.",
    rating: 4.8,
    feature: true,
  },
  {
    id: 4,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    cover: "https://img.freepik.com/free-vector/flat-design-book-cover-template_23-2149445464.jpg",
    description: "A futuristic novel that explores the dangers of a technologically advanced and emotionally detached society.",
    rating: 4.3,
    feature: false,
  },
  {
    id: 5,
    title: "Moby Dick",
    author: "Herman Melville",
    year: 1851,
    cover: "https://img.freepik.com/free-vector/hand-drawn-book-cover-template_23-2149452173.jpg",
    description: "The narrative of Captain Ahab’s obsessive quest to kill the white whale, Moby Dick.",
    rating: 4.1,
    feature: false,
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    cover: "https://img.freepik.com/free-vector/romantic-novel-book-cover-template_23-2149445473.jpg",
    description: "A romantic novel that charts the emotional development of Elizabeth Bennet.",
    rating: 4.9,
    feature: true,
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    cover: "https://img.freepik.com/free-vector/minimal-book-cover-template_23-2149452189.jpg",
    description: "A story about teenage alienation and loss of innocence in post-war America.",
    rating: 4.0,
    feature: false,
  },
  {
    id: 8,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: 1953,
    cover: "https://img.freepik.com/free-vector/fantasy-book-cover-template_23-2149452178.jpg",
    description: "A dystopian novel where books are outlawed and 'firemen' burn any that are found.",
    rating: 4.4,
    feature: true,
  },
  {
    id: 9,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    year: 1847,
    cover: "https://img.freepik.com/free-vector/book-cover-template_23-2149445481.jpg",
    description: "A novel following the experiences of Jane Eyre, including her growth and love life.",
    rating: 4.5,
    feature: false,
  },
  {
    id: 10,
    title: "Animal Farm",
    author: "George Orwell",
    year: 1945,
    cover: "https://img.freepik.com/free-vector/vintage-cover-template_23-2149445470.jpg",
    description: "An allegorical novella about a group of farm animals who rebel against their human farmer.",
    rating: 4.6,
    feature: true,
  },
  {
    id: 11,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    cover: "https://img.freepik.com/free-vector/fantasy-book-cover-template_23-2149452167.jpg",
    description: "The tale of Bilbo Baggins, a hobbit who joins a quest to reclaim treasure from a dragon.",
    rating: 4.8,
    feature: true,
  },
  {
    id: 12,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    cover: "https://img.freepik.com/free-vector/hand-drawn-book-cover-template_23-2149445479.jpg",
    description: "A psychological drama exploring morality, guilt, and redemption.",
    rating: 4.4,
    feature: false,
  },
  {
    id: 13,
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    cover: "https://img.freepik.com/free-vector/book-cover-template_23-2149452192.jpg",
    description: "A philosophical novel about a young shepherd's journey to find treasure.",
    rating: 4.7,
    feature: true,
  },
  {
    id: 14,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    cover: "https://img.freepik.com/free-vector/abstract-book-cover-template_23-2149445482.jpg",
    description: "A story about vanity, moral corruption, and eternal youth.",
    rating: 4.3,
    feature: false,
  },
  {
    id: 15,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    year: 1847,
    cover: "https://img.freepik.com/free-vector/literature-book-cover-template_23-2149452166.jpg",
    description: "A tragic tale of love, revenge, and obsession set on the Yorkshire moors.",
    rating: 4.2,
    feature: false,
  },
  {
    id: 16,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: 2003,
    cover: "https://img.freepik.com/free-vector/wattpad-cover-template_23-2149445477.jpg",
    description: "A powerful story of friendship, betrayal, and redemption set in Afghanistan.",
    rating: 4.9,
    feature: true,
  },
  {
    id: 17,
    title: "Life of Pi",
    author: "Yann Martel",
    year: 2001,
    cover: "https://img.freepik.com/free-vector/flat-design-book-cover-template_23-2149452181.jpg",
    description: "A young boy survives a shipwreck and is stranded on a lifeboat with a Bengal tiger.",
    rating: 4.6,
    feature: false,
  },
  {
    id: 18,
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    cover: "https://img.freepik.com/free-vector/vintage-book-cover-design_23-2149445480.jpg",
    description: "A gothic novel about a scientist who creates a sentient creature from corpses.",
    rating: 4.3,
    feature: false,
  },
  {
    id: 19,
    title: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    cover: "https://img.freepik.com/free-vector/gothic-book-cover-template_23-2149452187.jpg",
    description: "A chilling story of vampires, bloodlust, and the battle between good and evil.",
    rating: 4.5,
    feature: false,
  },
  {
    id: 20,
    title: "The Book Thief",
    author: "Markus Zusak",
    year: 2005,
    cover: "https://img.freepik.com/free-vector/contemporary-book-cover-template_23-2149452194.jpg",
    description: "A historical novel narrated by Death, following a young girl in Nazi Germany.",
    rating: 4.8,
    feature: true,
  },
];
